### ISSUE TITLE
Merge .csv files for all years

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/GSODR#11]
@PRoyal22 suggested to be able to merge CSV files for all years of a single station that are queried.

This is a desirable and easy to implement feature for a single station and include in the `get_GSOD()` function. To do this for all years queried for the complete GSOD set or agroclimatology might not be desirable simply due to the size of the final files that are generated for each year.

**Comment by pat-s** [comment]
One option could be:
- if `merge = TRUE` and `length(years)` > certain threshold `x`
  , than the output file gets compressed by a certain compression mechanism and/or a warning is thrown that the desired settings might result in a large output file. 

An example for file size: I queried three stations for the time period 1973 - 2015 using the GSOD web page. What you get back is one file containing all the data. Therefore, we have 43*3  = 129 years which results in a 6.3 MB large .csv file (which is quite okay!). If this gets compressed, I guess the threshold for receiving a "too large file" can be seen at somewhere around 1000 years (just a random number) (if the size scaling is linear).

Just some thoughts! :)

**Comment by adamhsparks** [comment]
Not bad, I'm not too concerned with single stations. More with the whole dataset file sizes.

**Comment by adamhsparks** [comment]
Added ability to merge output files for several years into one when selecting a single station with commit [1663fac](https://github.com/adamhsparks/GSODR/commit/01d5badef96e74cf45d00c706dca4ed749041c9f)
