### ISSUE TITLE
Precipitation is not reported in mm

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/GSODR#13]
Precipitation is calculated incorrectly as cm not mm.

This commit fixes that.
[8d09f2257f982de4fa6ea492248124acbe0a4fc7](https://github.com/adamhsparks/GSODR/commit/8d09f2257f982de4fa6ea492248124acbe0a4fc7)

Thanks to Gwenael Giboire (@GwenGitHub) for reporting this bug.

**Comment by adamhsparks** [comment]
Invalid values were returned.

Missing values in PRCP were not being correctly identified upon import and conversion was off by factor 100.

Bugs fixed with this commit, [1721752e313972c85f2577c7a778eca46052fadb](https://github.com/adamhsparks/GSODR/commit/1721752e313972c85f2577c7a778eca46052fadb)

**Comment by GwenGitHub** [comment]
Thanks Adam for your prompt response and updatings on the fly
