### ISSUE TITLE
paper.md lacks all authors

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/GSODR#17]
@thengl, I don't know what's happened, but your edits to the paper.md file have gone missing and I cannot find them in git anywhere.

I moved the `/paper` directory to `/inst/paper` and I think perhaps you were editing the version in the previous location and the changes got clobbered with the moving directories around?

Can you check and update your information and edits in the current location of the file? I see that there is a .png file in the `/paper` directory. That directory should not exist in the current master or devel branches.

**Comment by thengl** [comment]
I have worked on the "devel" branch. Sorry for the troubles, but as far as I can see, the paper.md is still at: https://github.com/adamhsparks/GSODR/blob/devel/inst/paper/paper.md. I definitively did not work in that file.

**Comment by adamhsparks** [comment]
Hi Tom,
Perhaps I was mistaken. I thought you edited paper.md to include your affiliation and ORCID?

If not, please supply that information.

**Comment by thengl** [comment]
I have not edited paper.md. My affiliation is:

T. (Tom) Hengl
Researcher @ ISRIC - World Soil Information
Mail: ISRIC - World Soil Information P.O. Box 353, 6700 AJ Wageningen, The Netherlands
Location: Droevendaalsesteeg 3 (Building 101 / GAIA) room: C.002
Tel: +31(0)317-484199
Url: http://www.wageningenur.nl/en/Persons/dr.-T-Tom-Hengl.htm
Network: http://profiles.google.com/tom.hengl
Publications: http://scholar.google.com/citations?user=2oYU7S8AAAAJ
ORCID ID: http://orcid.org/0000-0002-9921-5129

**Comment by adamhsparks** [comment]
@thengl, no worries, I must have imagined it. :)

I've added your information to the file. Please check and confirm that it's correct.
