### ISSUE TITLE
Documentation link is incorrect

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/GSODR#21]
@sckott,

I didn't edit the link to the webpage before moving the repository from my page to ropensci and now the link points back at the old location but I do not have the ability to edit it.

> Global Summary Daily Weather Data in R http://adamhsparks.github.io/GSODR/

should be

> Global Summary Daily Weather Data in R http://ropensci.github.io/GSODR/

**Comment by sckott** [comment]
@adamhsparks try it again, refresh page

**Comment by adamhsparks** [comment]
All good and updated now.

Thanks!
