### ISSUE TITLE
Updated badge links but Travis build fails

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/GSODR#22]
@sckott,
I'm unable to switch on the Travis to build this package since I'm not an administrator any longer now so the build fails.

I've updated the links in the documentation. Just need to fix things up on the Travis side of things, I think?

**Comment by adamhsparks** [comment]
I've resynced my Travis with GitHub and enabled the ropensci/GSODR.

Thanks.

**Comment by sckott** [comment]
just checked it, everything should be good to go - ah, see you closed it, nice
