### ISSUE TITLE
Low precipitation values

### ISSUE THREAD

**Issue by tosinaregbs** [ropensci/GSODR#23]
The precipitation values appear lower than expected/observed and some of data are also missing. Is there anything I can do about these low values? How do I reduce the number of values removed from the plots?

![rplot01](https://cloud.githubusercontent.com/assets/23707719/22108314/985a6438-de63-11e6-9f8b-23e2b195a57c.png)
![western precipitation](https://cloud.githubusercontent.com/assets/23707719/22108322/9fb4ad10-de63-11e6-8e38-b409aedc501c.png)

**Comment by adamhsparks** [comment]
About the values, could you share your code with me that you used to generate these data/graphs?

About the missing data, unless you've set your value to filter stations missing more than 0 days, you're getting all the data available in the GSOD data set. If it's set to more than 0 it will simply not report that particular station/year combination. When I checked right now Kigoma is missing most values for the years 1980-1985:  
> 1980:27
 1981:31 
 1982:17
 1983:84
 1984:80
 1985:44

I can't do anything about that. The data aren't there on the server.

**Comment by tosinaregbs** [comment]
See attached file.
![capturemv](https://cloud.githubusercontent.com/assets/23707719/22175195/49cef744-e001-11e6-9822-5be99934c06f.PNG)

**Comment by adamhsparks** [comment]
@tosinaregbs, I assume that you've validated that the daily values are too low for each day against another dataset as well?

**Comment by tosinaregbs** [comment]
Dear Sir,
I just checked the worldbank database 
http://sdwebx.worldbank.org/climateportal/index.cfm?page=downscaled_data_download&menu=historical

The values appear higher.

**Comment by adamhsparks** [comment]
@tosinaregbs, since you've not actually given me any comparisons to look at and the data in your link seem to be an annual value for the whole country not individual stations, I'm not sure what to advise other than there's an issue with the data from the GSOD that doesn't seem to be something that's resolvable as it's the data itself.

I don't see how this is an issue with the GSODR package itself that I have any control over but I'm still checking my code to be sure.

**Comment by adamhsparks** [comment]
I've compared stations here in Australia in the GSOD data to BOM data. They match very closely, not exact but within ~100mm/year.

Also in a very quick Google search I found a paper that suggests that the way GSOD measures precipitation, it is likely to lead to differences in the daily totals.

> In contrast with the tendency for increasing water vapor and precipitation elsewhere in the Arctic, Nickl et al. [2010] found generally decreasing annual precipitation over large parts of Alaska between 1993 and 2002, which they attributed to increasing contributions by Global Summary of the Day (GSOD) data. These stations are numerous, so they may more appropriately capture low precipitation in dry areas, but GSOD compiles data differently than other networks, which can lead to differences in daily precipitation totals [National Climatic Data Center (NCDC), 2013].

McAfee, S., G. Guentchev, and J. Eischeid (2014), Reconciling precipitation trends in Alaska: 2. Gridded data analyses, _J. Geophys. Res. Atmos._, **119**, 13,820–13,837, doi:10.1002/2014JD022461.

I'd suggest that you further research the issue as it does not seem to be related to the GSODR package, but rather the GSOD data itself.

Cheers!
