### ISSUE TITLE
Typo resulting in "Error in readChar [...]"

### ISSUE THREAD

**Issue by sachserf** [ropensci/GSODR#31]
There is a typo in line 160 of get_GSOD():
- load(system.file("extdata", "country_list.Rda", package = "GSODR"))
- Rda should be rda

Resulting in the following error:

Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '', probable reason 'No such file or directory'

-----------------

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by adamhsparks** [comment]
Thanks @sachserf 

Fixed, a new release will be on CRAN soon with this and another bugfix
