### ISSUE TITLE
get_GSOD not downloading data from selected year

### ISSUE THREAD

**Issue by emdelponte** [ropensci/GSODR#34]
-  I am trying to download data for a specific year-station. For example:

`Lond_2005 <- get_GSOD(years = 2005, station = "837660-99999")`

It is returning only 2010 irrespectively of the chosen year.

`$ YEAR             <chr> "2010", "2010", "2010", "2010", "2010", "2010",...`

- Is there a way to download data from multiple/interval of years? something like `c(2010:2014)`

**Comment by emdelponte** [comment]
I discovered something. For some reason the new data frame is not downloading the requested year. In the example below, it keeps loading the 2005 year for the newly created `get2` data frame.

`get1 <- get_GSOD(years = 2005, station = "955510-99999")`

`get2 <- get_GSOD(years = 2006, station = "955510-99999")`

**Comment by adamhsparks** [comment]
Well that's interesting. I'll look into it. Thanks Emerson.

**Comment by emdelponte** [comment]
I did more tests and notice that the new data frame preserves the data from the previous one. So, if there are 365 observations in `get1`, `get2`(from the example above) will have double! It is working as `rbind` function.

Also noticed that BR stations did not have PRCP data for the years I want. Also, some stations have limited coverage :(

**Comment by adamhsparks** [comment]
I've fixed issue #2.

Boarding my plane now. Will push to GH later

**Comment by adamhsparks** [comment]
In devel branch now

**Comment by adamhsparks** [comment]
Well, I thought it was fixed, apparently not

**Comment by adamhsparks** [comment]
Hi @emdelponte, 
I think I've fixed the second issue, which I'm guessing is related to the 1st, I think you might have run a query for 2010 before 2005?

I think this first issue is related to #33, I still need to fix that.

The fix for #34 is in the Main branch now.

**Comment by adamhsparks** [comment]
As for your question about multiple years, yes, a vector like 2005:2010 will work to download multiple years.
