### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by ssomani10** [ropensci/GSODR#75]
Is there a way to do batch processing, if I have multiple stations.  I have tried using a vector and having the station[1] in the get_gsod, which it did not take and I also tried using the paste command but was getting this error:  **We've tried to get the file(s) you requested six times, but the server is not responding, so we are unable to process your request now. Please try again later.**

Thanks,

Shaffiq

**Comment by adamhsparks** [comment]
Hi Shaffiq,
What version are you using of GSODR? This error message doesn't appear in the latest version, which supports the NCEI's most recent version of the GSOD data interface.

I'm guessing the version you're using is outdated, does not work and is not supported any longer.

**Comment by ssomani10** [comment]
Thanks.  I did update it.  I thought I was obtaining couple of issues, but I compared to the GSOD data and everything seems to be okay.   Thanks so much
