### ISSUE TITLE
reformat_GSOD() does not use file_list input parameter

### ISSUE THREAD

**Issue by oxalisids** [ropensci/GSODR#78]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

See reformat_GSOD() source code below. Object file_list is an input parameter, but it is reassigned automatically when dsn is not NULL, and input value is ignored. I suppose file_list is only used when input dsn is NULL, but that is not clear in the package documentation, and the required format for file_list is also not clear from documentation. Thank you for the package!

Alison 
_____________________________________________
reformat_GSOD <- function (dsn = NULL, file_list = NULL) 
{
    isd_history <- NULL
    load(system.file("extdata", "isd_history.rda", package = "GSODR"))
    setkeyv(isd_history, "STNID")
    if (!is.null(dsn)) {
        file_list <- list.files(path = dsn, pattern = "^.*\\.csv$", 
            full.names = TRUE)
        if (length(file_list) == 0) 
            stop("No files were found, please check your file location.")
    }
    GSOD_XY <- .apply_process_csv(file_list, isd_history)
    return(GSOD_XY)
}

**Comment by adamhsparks** [comment]
Thanks for pointing this out!

I've updated the documentation and modified the function's behaviour to emit a message when both are specified.

Is this more helpful?

https://github.com/ropensci/GSODR/commit/8d40b4261267061eddf9aa768597e9858aab7861

**Comment by adamhsparks** [comment]
Closing issue. Feel free to reopen if this hasn't addressed it fully.
