### ISSUE TITLE
Country list problem

### ISSUE THREAD

**Issue by rogarui** [ropensci/GSODR#80]
Hi, 

When i'm trying to get the country_lsit with this code:

`load(system.file("extdata", "country_list.rda", package = "GSODR"))`

R shows me the next error:

Error in readChar(con, 5L, useBytes = TRUE) : 
  no se puede abrir la conexión
Además: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '', probable reason 'Invalid argument'

Any idea what is going wrong? i'm trying the same with:

`load(system.file("extdata", "isd_history.rda", package = "GSODR"))`

and is working fine..

Thanks in advance!

**Comment by adamhsparks** [comment]
Hi,
This file does not exist in the package, hence the error.
